bot:
  - Laptops
category:
  - ';'
keywords:
  - '8750H;9300H;9400H;6700HQ;1050;1060;1070;GTX 1080;RX560X;RX5600M;RX5700M;RX5800M;RX580;RX590;RX6800M;RTX;Pro 2018;Pro 2019;9750H;Ryzen 5 4600H;Ryzen 7 4800H;regex:(?=.*\b M1\b)(?=.*\bMacBook\b);regex:\b32\s*g[bo]\s*(de\s*)?ram\b;!M6700'
  - '1650;1660;GTX 1080;RX5500M;RX5600M;RX6400M;RX6500M;RX580;RX590;RX6800M;Pro 2020;10750H;10850H;10980HK;11900H;11980HK;12700H;Ryzen 5 5600H;Ryzen 7 5800H;Ryzen 9 5900H;Ryzen 9 5900HX;Ryzen 9 6900HX;regex:(?=.*\b M1 Pro\b)(?=.*\bMacBook\b);regex:\b64\s*g[bo]\s*(de\s*)?ram\b'
  - '2060;2070;2080;3050 ;RTX;i9;I9;RX5700M;RX6500M;RX6600M;RX6700M;RX6800M;Pro 2021;12900H;12950H;regex:(?=.*\b M2\b)(?=.*\bMacBook\b);!N3050'
  - '!N3060;!N4050;3060;3070;4050;RX6600M;RX6700M;RX6800M;RX7600M;RX7700M;12900;12800;12700;14500;13700;Ryzen 7 7745HX;Ryzen 9 7845HX;Core Ultra 5;Core Ultra 7;Pro 2022;regex:(?=.*\b M3\b)(?=.*\bMacBook\b);regex:(?=.*\b M2 Pro\b)(?=.*\bMacBook\b)'
  - '3080;4060;4070;4080;RX6800M;RX6850M XT;RX7600M;RX7700M;RX7800M;RX7900M;14900;14700;13980;13950;13900;13800;12950;12900;Ryzen 9 7945HX;Ryzen 9 7945HX3D;Core Ultra 9;Pro 2023;regex:(?=.*\b M4\b)(?=.*\bMacBook\b);regex:(?=.*\b M3 Pro\b)(?=.*\bMacBook\b)'
  - '5070;5080;5090;4090;RX7800M;RX7900M;RX7950M;Ryzen AI 9;Ryzen AI 7;Pro 2024;!optiplex;regex:(?=.*\b M3 Max\b)(?=.*\bMacBook\b);regex:(?=.*\b M4 Pro\b)(?=.*\bMacBook\b);regex:(?=.*\b M4 Max\b)(?=.*\bMacBook\b)'
  - 'msi;gigabyte;gaming;rtx;rog ;strix;tuf ;scar;victus;legion;omen;nitro;alienware;predator;helios;triton;blade;razer;alpha;aurora'
  - 144Hz;165Hz;240Hz;300Hz;OLED;QHD;2560x1440;32GB RAM;32 Go RAM;64GB RAM;64 Go RAM;Quadro;Xeon
page_count: 1
price_ranges:
  - 150-375
  - 225-450
  - 300-600
  - 450-750
  - 600-1050
  - 900-1800
  - 300-1500
  - 300-750
bot_blocklist:
  - for parts
  - not working
  - parts only
  - sold as is
  - as-is
  - water damage
  - liquid damage
  - spare parts
  - local pickup only
  - pour pièces
  - pour pieces
  - défectueux
  - defectueux
  - dégât d'eau
  - ramassage seulement
block_lower_range:
  - False
ebay_category:
  - 175672
get_description: True
item_location_provinces:
  - QC
  - Quebec
  - Québec
  - ON
  - Ontario
