bot:
  - Tablets
category:
  - ';'
ebay_category:
  - 171485
get_description: False
keywords:
  - 'ipad 7;ipad 8;tab s6;!lite;!cover'
  - 'ipad 9;ipad 2020;tab s7;!fe;!cover'
  - 'ipad 10;ipad 2021;ipad air 3;tab s7 plus;tab s8;!cover;!10.2;!10,2'
  - 'ipad air 4;ipad 2022;ipad pro 10.5;!cover'
  - 'ipad air 5;ipad air m1;ipad pro 11 2020;tab s8 ultra;tab s9;!cover;!fe;Tab s8 plus'
  - 'ipad pro 11 2021;ipad pro m1;tab s9 plus;!cover'
  - 'ipad pro 12.9 2021;ipad pro m2;tab s9 ultra;!cover'
  - 'ipad pro m4;ipad pro 2024;tab s10 ultra;tab s10;tab s 10 plus;tab s11;tab s 11;!lite;!fe;!cover'
page_count: 1
price_ranges:
  - 50-110
  - 90-180
  - 140-260
  - 150-260
  - 250-420
  - 350-550
  - 450-700
  - 500-1300
ebay_filters: 'buyingOptions:{FIXED_PRICE},itemLocationCountry:CA,deliveryCountry:CA,price:[50..2500],priceCurrency:CAD'
bot_blocklist:
  - for parts
  - not working
  - parts only
  - sold as is
  - icloud
  - activation lock
  - mdm
  - screen only
  - display only
  - cracked screen
  - broken screen
  - spare parts
  - Ipad pencil
  - local pickup only
  - pour pièces
  - pour pieces
  - défectueux
  - defectueux
  - écran brisé
  - ecran brise
  - écran fissuré
  - ecran fissure
  - ramassage seulement
item_location_provinces: []
kijiji_url: https://www.kijiji.ca/b-ipad-tablet/canada/c767l0
kijiji_price: 50-2500
